#!/bin/bash
########################################################
#
# Copyright 2016, All Rights Reserved.
#
# Code licensed under the MIT LICENSE:
# https://github.com/randhson/dotfiles/blob/master/LICENSE
#
# @author Randson Nunes <randhson@ig.com.br>
#
########################################################

echo '      _       _    __ _ _           '
echo '     | |     | |  / _(_) |          '
echo '   __| | ___ | |_| |_ _| | ___  ___ '
echo '  / _` |/ _ \| __|  _| | |/ _ \/ __|'
echo ' | (_| | (_) | |_| | | | |  __/\__ \'
echo '  \__,_|\___/ \__|_| |_|_|\___||___/'
echo '                                    '

## Variables
dir=~
dotfiles="$dir/.dotfiles"

echo "[?] What is your BI? [32bits or 64bits]"
read BI

echo "[?] Which Git name would you like to use?"
read git_username

echo "[?] Which Git email would you like to use?"
read git_email

######################################################## Essentials

### cURL
sudo apt-get install curl

######################################################## Shell

### ZSH
sudo apt-get install zsh
sudo apt-get install git-core

### Oh My ZSH
wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
chsh -s `which zsh`

######################################################## Editors

### Sublime Text 3
sudo add-apt-repository ppa:webupd8team/sublime-text-3
sudo apt-get update
sudo apt-get install sublime-text-installer

######################################################## NodeJS
 
### NodeJS
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install -g nodejs

### Gulp
sudo npm install -g gulp
 
### JSHint
sudo npm install jshint

######################################################## Ruby

### Ruby
sudo apt-get install ruby ruby-dev make

### Jekyll
sudo gem install jekyll --no-rdoc --no-ri



######################################################## General

### Google Chrome Browser
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sudo apt-get update
sudo apt-get install google-chrome-stable -y

### VLC Media Player
sudo apt-get install vlc

### GParted
sudo apt-get install gparted

### Virtual Box
sudo apt-get install virtualbox

### Dropbox
cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
~/.dropbox-dist/dropboxd

### Systemback
sudo apt-add-repository ppa:nemh/systemback
sudo apt-get update
sudo apt-get install systemback

